# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.1.0

definitions:
          caches:
            npm: ~/.npm

pipelines:
  default:
    - step:
        caches:
          - npm
          - node
        script:
          - git submodule init
          - git submodule update
          - git submodule foreach 'git submodule init && git submodule update'
          - cd multimediaobject/src/libs/check/ && git submodule init && git submodule update && cd ../../../../
          - cp multimediaobject/src/config/config.tpl.js multimediaobject/src/config/config.js
          - sed -i 's/{{ globalnamespace }}/MultimediaObjectEditor/g' multimediaobject/src/config/config.js
          - sed -i 's/{{ namespace }}/_s4mConfig/g' multimediaobject/src/config/config.js
          - sed -i 's/{{ container }}/scene/g' multimediaobject/src/config/config.js
          - cd editor && npm install
          - cd ../multimediaobject && npm install
          - cd ../ && npm test
