# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.1.0

definitions:
          caches:
            npm: ~/.npm

pipelines:
  default:
    - step:
        caches:
          - npm
          - node
        script: # Modify the commands below to build your repository.
          - git submodule init
          - git submodule update
          - cd editor
          - npm install
          - cd ../
          - npm install
          - npm test
          - npm run doc
